# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxTest
	pod 'RxSwift'
  	pod 'RxCocoa'
	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'SVProgressHUD'


  target 'RxTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
